### ISSUE TITLE
Allow chaining comma operators

### ISSUE THREAD

**Issue by litherum** [gpuweb/WHLSL#119]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=186072:

At 2018-05-29T23:48:18Z, rmorisset@apple.com wrote:
```WHLSL
int f() {
    int x;
    x = 42;
    x *= 2, x += 1, x *= 3;
    return x;
}
```
fails with a parser error, yet works if either of the ',' operator are replaced by a ';'.
It should be accepted, there is no reason for chained comma operators to be refused.

**Comment by RobinMorisset** [comment]
Has been fixed in the C++ implementation.
