### ISSUE TITLE
CFG analysis framework should know how to handle the interaction between continue, break, loops, and switches

### ISSUE THREAD

**Issue by litherum** [gpuweb/WHLSL#179]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=177172:

At 2017-09-19T18:16:21Z, fpizlo@apple.com wrote:
I think this means using a visitor to extract a CFG and then analyzing the CFG.

We could make the CFG extractor reusable.

**Comment by litherum** [comment]
At 2017-09-19T18:19:12Z, fpizlo@apple.com wrote:
I think we should disallow case fall-through in switch statements. This means ensuring that all paths down a case end in a break.

For now, I'm implementing C semantics, which treat fallthrough as a feature.

**Comment by litherum** [comment]
At 2018-08-30T00:08:13Z, mmaxfield@apple.com wrote:
"and then analyzing the CFG"

And doing what with it?

**Comment by RobinMorisset** [comment]
This was solved in both spec and implementation a long time ago.
See WHLSLStatementBehaviorChecker.cpp in the implementation, and the typing-statements section of the spec.
