### ISSUE TITLE
Representable values of floating point numbers are not spec'ed

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WHLSL#237]
index.rst describes "half" as "A 32-bit floating-point number."

More seriously, for both half and float, it says "See below for details on representable values."  But there is no such description in the doc.  It would be nice to reference something like IEEE 754

**Comment by litherum** [comment]
We need to describe how things like denormals work (or don't).

**Comment by litherum** [comment]
Looks like the SPIR-V spec doesn't say anything about denormals or special inf/nan/-0 handling. We can probably be just as precise.
