### ISSUE TITLE
Mismatched input '1' expecting CoreDecimalIntLiteral

### ISSUE THREAD

**Issue by dj2** [gpuweb/WHLSL#241]
I have a small program which uses the Antlr g4 to build a WHLSL parser (I am unable to use the JS version as it does not run with Node). When parsing https://github.com/KhronosGroup/SPIRV-Cross/blob/master/reference/opt/shaders-hlsl/comp/image.comp I receive:

line 59:12 mismatched input '1' expecting CoreDecimalIntLiteral

**Comment by RobinMorisset** [comment]
Thank you for these reports. This one is a clear bug in the grammar, I've fixed it.
