### ISSUE TITLE
Token recognition error

### ISSUE THREAD

**Issue by dj2** [gpuweb/WHLSL#244]
I have a small program which uses the Antlr g4 to build a WHLSL parser (I am unable to use the JS version as it does not run with Node). When parsing https://github.com/KhronosGroup/SPIRV-Cross/blob/master/reference/shaders/desktop-only/frag/hlsl-uav-block-alias.asm.frag I receive:

line 1:0 token recognition error at: '#'
line 1:9 no viable alternative at input 'version450'

**Comment by litherum** [comment]
This is GLSL source code.
