### ISSUE TITLE
index.rst: What unicode encoding do WHLSL shaders use?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WHLSL#266]
> Shaders exist as a Unicode string, and therefore support all the code points Unicode supports.

What Unicode encoding is expected?  I presume UTF-8?  The spec should say so.

**Comment by litherum** [comment]
https://github.com/gpuweb/WHLSL/issues/233

**Comment by grorg** [comment]
At the moment we don't define a file format, so as @litherum said, it's just the WebGPU API that matters (and we suggest DOMString).

However, we do have .whlsl files in our repository, and they are processed as UTF-8 (I'm fairly certain). If we formalize this, we can document it.

**Comment by annevk** [comment]
You cannot serialize DOMString as UTF-8 however so you might want to start using USVString...
