### ISSUE TITLE
index.rst does not describe native, restricted or space

### ISSUE THREAD

**Issue by dj2** [gpuweb/WHLSL#298]
These three items are listed as keywords but don't appear anywhere else in the file.

**Comment by RobinMorisset** [comment]
Thanks for finding this.
- native is currently used internally for implementing the standard library. I temporarily moved it to the list of keywords reserved for future extension, but we could get rid of it altogether.
- restricted was used when the language had generics. I put it in the list of keywords reserved for future extension, in case we decide some day to add generics back in.
- space was apparently used in the 'semantics' part of the grammar (something we inherit from HLSL and that is the most terribly named thing I've ever seen), but is not currently in use. It went with the other two in the "for future extension" category, but like native I am open to removing it altogether.

**Comment by dj2** [comment]
Moving them to the reserved list is fine, makes clear that they aren't currently used. Thanks.
