### ISSUE TITLE
Remove the vector type syntax vector<blah, N>

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WHLSL#302]
E.g. vector<float,2> currently is a synonym for float2.

HLSL uses float2.   I don't see a good reason to have a second syntax for a standard concept in HLSL.  It introduces noise into the spec, and useless variation vs. existing shaders.

**Comment by litherum** [comment]
HLSL also uses vector<float, 2> https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-vector

**Comment by dneto0** [comment]
oof.  Indeed.  

Mea culpa.  
Ignorantiae meae.
