### ISSUE TITLE
The reference implementation treats post-{increment/decrement} as pre-{incr/decr} when there is a field setter

### ISSUE THREAD

**Issue by RobinMorisset** [gpuweb/WHLSL#308]
The reference implementation currently behaves really weirdly on post-incrementing a field of a struct with an overriden setter (and getter).
It correctly uses the getter for having the current value, increment it, uses the setter for updating it.. but somehow returns the new value instead of the old one.
I believe this is a bug in the reference implementation.

Example:
```
struct Foo {
  int z;
}
int operator.w(Foo foo) {
  return 8;
}
Foo operator.w=(Foo foo, int value) {
  foo.z = value;
return foo;
}
int bar() {
  Foo foo;
  foo.z = 3;
  int value = foo.w++;
  return value*100 + foo.z*10 + foo.w;
}
```
Calling bar() return 998 instead of 898 as I would expect.

**Comment by litherum** [comment]
This should be fixed.
