### ISSUE TITLE
"void" is probably allowed as a variable type or as a parameter type

### ISSUE THREAD

**Issue by litherum** [gpuweb/WHLSL#320]
We should make sure that this is illegal.

**Comment by litherum** [comment]
Also, we should consider something like

```WHLSL
void foo() {
    ...
}
void bar() {
    ...
    return foo();
}
```

**Comment by RobinMorisset** [comment]
I believe the spec already does the right thing here (forbid it as variable/parameter type, allow it as a return type and allows the example program you put).
I have not verified either of the implementations.

**Comment by litherum** [comment]
Migrated to https://bugs.webkit.org/show_bug.cgi?id=200751
