### ISSUE TITLE
Consider not supporting boolean matrixes

### ISSUE THREAD

**Issue by polarina** [gpuweb/WHLSL#358]
Commit cd9d5f8481edbebb2e62e4979ae4f73b7ac8ddd9 added support for boolean matrixes.

SPIR-V does not allow boolean matrixes. Section 2.16.1, Universal Validation Rules, Data Rules, states:

> Matrix types can only be parameterized with floating-point types.

**Comment by litherum** [comment]
Good idea. Cross compilation between WSL and SPIR-V is important.
