### ISSUE TITLE
ParseConstexpr is very general

### ISSUE THREAD

**Issue by litherum** [gpuweb/WHLSL#79]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=189029:

At 2018-08-27T23:24:39Z, mmaxfield@apple.com wrote:
It's called in a few places:

vector<float, 4> // that "4" is a constexpr
float[10] // that "10" is a constexpr

enum asdf : int {
    XYZ = -3 // that "-3" is a constexpr
}

switch (foo) {
    case MyEnum.XYZ: // that "MyEnum.XYZ" is a constexpr
}

Because of all that, parseConstexpr can return something like operator-((x + y).z)

We should do a bunch of filtering to make sure the right kind of constexprs are allowed in the various places where they are allowed.

**Comment by RobinMorisset** [comment]
Fixed when we moved to the new parser.
