### ISSUE TITLE
ParseTypeArguments calls parseExpression()

### ISSUE THREAD

**Issue by litherum** [gpuweb/WHLSL#84]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=189022:

At 2018-08-27T23:05:20Z, mmaxfield@apple.com wrote:
It calls parseConstexpr(), which calls parseTerm(), which calls parseExpression(). We don't want to allow things like

int x = 2;
vector<float, (x + 1)> v;

We need to either change how the parser works, or add validation that typeArguments can only be certain things.

**Comment by RobinMorisset** [comment]
This was only true of the js parser.
